version: "3.8"
services:
  mariadb:
    image: mariadb:10.5.5
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: accounts
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db-migration:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  mariadb-data:
