app:
  listen: 0.0.0.0:8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 15s

logging:
  level: debug
  output:
    - stdout
    - app.log

mariadb:
  url: user:password@tcp(127.0.0.1:3306)/accounts
  max_open_connections: 100
  max_idle_connections: 10
  conn_max_lifetime: 120s

redis:
  url: localhost:6379
  pwd: pwd
